//! Proof-of-possession (PoP) for blind-relay pull (Phase 5).
//!
//! Client and relay share an ECDH secret via X25519, then bind it to a nonce and
//! destination token with SHA-256. The relay never learns the client's identity
//! secret and never decrypts mailbox blobs.

use rand::rngs::OsRng;
use rand::RngCore;
use sha2::{Digest, Sha256};
use x25519_dalek::{PublicKey, StaticSecret};

use crate::error::CoreError;
use crate::pubkey::ensure_canonical_public_key;
use crate::token::Token;

/// Domain separation for relay PoP proofs.
const POP_DOMAIN: &[u8] = b"encrypchat-pop-v1";

/// Length of challenge nonces and PoP digests.
pub const POP_PROOF_LEN: usize = 32;
pub const POP_NONCE_LEN: usize = 32;

/// Ephemeral X25519 keypair generated by the relay for one challenge.
#[derive(Clone)]
pub struct PopEphemeral {
    pub secret: [u8; 32],
    pub public: [u8; 32],
}

impl std::fmt::Debug for PopEphemeral {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PopEphemeral")
            .field("public", &hex::encode(self.public))
            .field("secret", &"<redacted>")
            .finish()
    }
}

/// Generate a fresh relay ephemeral keypair for a PoP challenge.
pub fn pop_generate_ephemeral() -> PopEphemeral {
    let secret = StaticSecret::random_from_rng(OsRng);
    let public = PublicKey::from(&secret);
    PopEphemeral {
        secret: secret.to_bytes(),
        public: public.to_bytes(),
    }
}

/// Generate a random 32-byte challenge nonce.
pub fn pop_generate_nonce() -> [u8; POP_NONCE_LEN] {
    let mut nonce = [0u8; POP_NONCE_LEN];
    OsRng.fill_bytes(&mut nonce);
    nonce
}

fn hash_pop(shared: &[u8; 32], nonce: &[u8], dest_token: &str) -> [u8; POP_PROOF_LEN] {
    let mut hasher = Sha256::new();
    hasher.update(POP_DOMAIN);
    hasher.update(shared);
    hasher.update(nonce);
    hasher.update(dest_token.as_bytes());
    let out = hasher.finalize();
    let mut proof = [0u8; POP_PROOF_LEN];
    proof.copy_from_slice(&out);
    proof
}

fn ct_eq(a: &[u8; 32], b: &[u8; 32]) -> bool {
    let mut diff = 0u8;
    for i in 0..32 {
        diff |= a[i] ^ b[i];
    }
    diff == 0
}

/// Client-side: ECDH(identity secret, relay ephemeral pub) → SHA-256 proof.
pub fn pop_proof(
    secret: &[u8; 32],
    peer_eph_pub: &[u8; 32],
    nonce: &[u8],
    dest_token: &str,
) -> Result<[u8; POP_PROOF_LEN], CoreError> {
    if nonce.is_empty() {
        return Err(CoreError::AuthFailed);
    }
    let token = Token::parse(dest_token)?;
    ensure_canonical_public_key(peer_eph_pub)?;
    let sk = StaticSecret::from(*secret);
    let peer = PublicKey::from(*peer_eph_pub);
    let shared = sk.diffie_hellman(&peer);
    Ok(hash_pop(shared.as_bytes(), nonce, token.as_str()))
}

/// Relay-side: ECDH(ephemeral secret, client pub) → compare proof.
pub fn pop_verify(
    eph_secret: &[u8; 32],
    client_pub: &[u8; 32],
    nonce: &[u8],
    dest_token: &str,
    proof: &[u8; POP_PROOF_LEN],
) -> Result<bool, CoreError> {
    if nonce.is_empty() {
        return Err(CoreError::AuthFailed);
    }
    let token = Token::parse(dest_token)?;
    // A non-canonical client key is an error, not a mismatch: the caller asked us to name a
    // key and there is no single name for that encoding.
    let derived = Token::from_public_key_bytes(client_pub)?;
    if derived.as_str() != token.as_str() {
        return Ok(false);
    }
    let sk = StaticSecret::from(*eph_secret);
    let peer = PublicKey::from(*client_pub);
    let shared = sk.diffie_hellman(&peer);
    let expected = hash_pop(shared.as_bytes(), nonce, token.as_str());
    Ok(ct_eq(&expected, proof))
}

/// True when `pubkey` hashes to the same token string (after parse/normalize).
///
/// A malformed token or a non-canonical `pubkey` is an error rather than `false`, so the
/// relay can answer "bad request" instead of "wrong key".
pub fn pubkey_matches_token(pubkey: &[u8; 32], dest_token: &str) -> Result<bool, CoreError> {
    let token = Token::parse(dest_token)?;
    let derived = Token::from_public_key_bytes(pubkey)?;
    Ok(derived.as_str() == token.as_str())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::identity::Identity;

    #[test]
    fn pop_roundtrip() {
        let id = Identity::generate();
        let eph = pop_generate_ephemeral();
        let nonce = pop_generate_nonce();
        let token = id.token();
        let proof = pop_proof(&id.to_secret_bytes(), &eph.public, &nonce, token.as_str()).unwrap();
        assert!(pop_verify(
            &eph.secret,
            &id.public_key_bytes(),
            &nonce,
            token.as_str(),
            &proof
        )
        .unwrap());
    }

    #[test]
    fn wrong_secret_fails() {
        let alice = Identity::generate();
        let bob = Identity::generate();
        let eph = pop_generate_ephemeral();
        let nonce = pop_generate_nonce();
        let token = alice.token();
        let proof = pop_proof(&bob.to_secret_bytes(), &eph.public, &nonce, token.as_str()).unwrap();
        assert!(!pop_verify(
            &eph.secret,
            &alice.public_key_bytes(),
            &nonce,
            token.as_str(),
            &proof
        )
        .unwrap());
    }

    #[test]
    fn pubkey_token_mismatch_rejected() {
        let alice = Identity::generate();
        let bob = Identity::generate();
        let eph = pop_generate_ephemeral();
        let nonce = pop_generate_nonce();
        let proof = pop_proof(
            &alice.to_secret_bytes(),
            &eph.public,
            &nonce,
            alice.token().as_str(),
        )
        .unwrap();
        assert!(!pop_verify(
            &eph.secret,
            &bob.public_key_bytes(),
            &nonce,
            alice.token().as_str(),
            &proof
        )
        .unwrap());
    }

    /// The relay pull gate (F-10). An alias of the client key names no one, so it must not
    /// reach the comparison as a plain "does not match" either.
    #[test]
    fn non_canonical_client_key_is_an_error_not_a_mismatch() {
        use crate::pubkey::test_vectors::{high_bit_alias, non_reduced_max, NON_REDUCED_ZERO};

        let alice = Identity::generate();
        let eph = pop_generate_ephemeral();
        let nonce = pop_generate_nonce();
        let token = alice.token();
        let proof = pop_proof(
            &alice.to_secret_bytes(),
            &eph.public,
            &nonce,
            token.as_str(),
        )
        .unwrap();

        for alias in [
            high_bit_alias(&alice.public_key_bytes()),
            NON_REDUCED_ZERO,
            non_reduced_max(),
        ] {
            assert!(matches!(
                pubkey_matches_token(&alias, token.as_str()),
                Err(CoreError::InvalidPublicKey)
            ));
            assert!(matches!(
                pop_verify(&eph.secret, &alias, &nonce, token.as_str(), &proof),
                Err(CoreError::InvalidPublicKey)
            ));
        }

        // The relay's own ephemeral gets the same treatment on the client side.
        assert!(matches!(
            pop_proof(
                &alice.to_secret_bytes(),
                &high_bit_alias(&eph.public),
                &nonce,
                token.as_str()
            ),
            Err(CoreError::InvalidPublicKey)
        ));
    }

    #[test]
    fn debug_redacts_eph_secret() {
        let eph = pop_generate_ephemeral();
        let rendered = format!("{eph:?}");
        assert!(rendered.contains("<redacted>"));
        assert!(!rendered.contains(&hex::encode(eph.secret)));
    }
}
